Use "is None" rathern than "== None"
Apparently things have changed in recent versions of numpy.  Without this
commit, the code errors out with:

	ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()